server:
  port: 0
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: homework-repo
          uri: lb://homework-repo
          predicates:
            - Path=/homework/**




